# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

version: "2"

linters:
  default: standard
  disable:
    # errcheck is too noisy for deferred Close() calls and test code
    - errcheck
  settings:
    govet:
      disable:
        # hostport check is too strict for simple internal services
        - hostport
    staticcheck:
      checks:
        - "all"
        - "-QF*" # disable quickfix suggestions
        - "-ST1000" # package comments not required
        - "-ST1003" # naming conventions (too strict)
  exclusions:
    rules:
      # Allow ineffectual assignments in test files (common for setup code)
      - path: _test\.go
        linters:
          - ineffassign
